### ISSUE TITLE
Is this theme now compatible to Q2A 1.7??

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#25]

**Comment by JoZ3** [comment]
Hi @gurjyot please read the other post before create one new...

- Cleanstrap and Q&A 1.7 + Bootstrap 3.3.1](https://github.com/Towhidn/CleanStrap/issues/24) 
- [Mobile menu not work with the lastest Q&A version](https://github.com/Towhidn/CleanStrap/issues/23)

**Comment by gurjyot** [comment]
@JoZ3 I am not having enough time to go through all the commits done before. I have not raised an issue, but just a question. I know that this question should be raised on q2a official forum but Towhidn is not coming on q2a from some time that's why that question is raised here.

**Comment by JoZ3** [comment]
@gurjyot spends more time writing the post that looking and especially when the list is small.
Please is not a good idea create duplicate commits, remember is only a developer behind this template...

**Comment by Towhidn** [comment]
navigation issue is addressed and I checked theme both on Q2A 1.6 & 1.7

**Comment by gurjyot** [comment]
Thanks for your reply @towhidn, now I will upgrade my site to q2a 1.7

Just one more thing, this theme is still having some unsolved issues, will you fix them soon??

**Comment by Towhidn** [comment]
I'm checking issues that was submitted here and some that I dug up. there are still 7 issues to fix. I'm planning to fix them by tomorrow(if everything goes well).
