### ISSUE TITLE
Why my gravatar is showing when by default avatar is selected

### ISSUE THREAD

**Issue by gurjyot** [Towhidn/CleanStrap#27]
I think there is some issue with gravatar and avatar showing in different places in this theme. By default avatar is selected but still my gravatar is showing in a lot of places on this site.

Have a look at the image below
![grat](https://cloud.githubusercontent.com/assets/6462850/6313097/8c81d656-b9c0-11e4-8861-f7112537ea02.png)

**Comment by Towhidn** [comment]
I'll check it and update in next version.

**Comment by Towhidn** [comment]
this issue is fixed

**Comment by gurjyot** [comment]
The problem is still there and the gravatars are showing as they were before. This update hadn't fixed the problem.

**Comment by Towhidn** [comment]
here is the order which avatars are extracted:
1. if it's an SSO or WP integration, avatars are extracted from related sections.
2. if user has uploaded an image, that image will be used.
3. if user hasn't uploaded an image and Gravatar is enabled(in Admin > users) gravatar will be used.
4. if gravatar is not enabled and there is a default image and it's activated, it will be used.
5. if there are no user uploaded images, gravatar is disabled, and there is no default image(or not activated), then no images will be used and you won't have an avatar.

the reason that Gravatar is used instead of default image(if gravatar is enabled) is because it's not worth(performance-wise) checking of existing or empty Gravatar.

code: https://github.com/Towhidn/CleanStrap/blob/master/cleanstrap/functions.php#L84

**Comment by gurjyot** [comment]
Ok, let me start checking all the points, 
1. I am not using SSO or wp integration
2. Not all users have uploaded an image, including me.
3. Gravatar can be used but it is not enabled
4. There is a default images but that is showing on some parts and in the rest gravatar is showing

To be more specific, gravatar is showing on users page, users profile, and new users widget. If this can help in solving the prob.

**Comment by Towhidn** [comment]
According to code's logic if gravatar is not enabled then it won't be used. can you send me an image of your User's option page("Admin > users").

also you might be interested to know that in new version a new option is added to "New Users Widget" that can be used to only show latest registered users who uploaded an image.

**Comment by gurjyot** [comment]
The Gravatar option is enabled in admin section but I have set a custom avatar, which should show everywhere. But the problem is that, at some places avatar is showing and at some places gravatar is showing. It is just like the way on your cleanstarp demo site. Where you have set an avatar but still gravatar is showing in new users widget.
